export const STORAGE_KEYS = {
  STREAK: 'STREAK_COUNT',
  LAST_DATE: 'LAST_COMPLETED_DATE',
  TASK: 'ONE_TASK',
  POINTS: 'TOTAL_POINTS',
  TIMER_END: 'TIMER_END_TIME',
  HISTORY: 'TASK_HISTORY',
} as const;
